- README.md
The PKGBUILD has moved from my Github to Manjaro GitLab.
> Update PKGBUILD link

- src-tauri/tauri.conf.json
Added window min and max size limit
✅ Closes: #37
> fix: 🐛 min and max window size

- src/components/NavbarComponent.tsx
- src/screens/Home.tsx
buttons and labels do not get blurred on header
✅ Closes: #38
> fix: 🐛 labels, buttons header override problem

- src/components/PackageRelated/PackageStatus.tsx
fixed if get error package installing process
✅ Closes: #41
> fix: 🐛 package status update

- src/components/PackageRelated/Packages.tsx
fixed jump category problem
✅ Closes: #43
> fix: 🐛 category name parse fixes

- src/components/HomeContent.tsx
- src/components/NavbarComponent.tsx
- src/components/PackageRelated/Packages.tsx
- src/components/SystemConfig/SystemConfig.tsx
- src/screens/Home.tsx
Fixed moving header bar problem and scrolling problem
✅ Closes: #54 #46
> fix: 🐛 header bar and scroll problem

- src/components/ResultComponent.tsx
fixed scroll to top problem
✅ Closes: #62
> fix: 🐛 result page scroll problem

- src/components/ResultComponent.tsx
- src/translations/en.json
blog button added
✅ Closes: #57
> feat: 🎸 added blog button

- src-tauri/src/main.rs
- src/components/PackageRelated/PackageStatus.tsx
- src/components/SystemConfig/KernelComponent.tsx
- src/components/SystemConfig/SystemFastestMirror.tsx
- src/components/SystemConfig/SystemUpdate.tsx
- src/index.tsx
- src/screens/Home.tsx
> fix: 🐛 added logs for installing process

- src/components/PackageRelated/PackageStatus.tsx
- src/components/SystemConfig/KernelComponent.tsx
added tooltips for icon buttons
✅ Closes: #45
> feat: 🎸 added tooltips

- src/components/StepButtons.tsx
react tour problem fixes when click next button
✅ Closes: #65
> fix: 🐛 react tour fixes

- src/components/PackageRelated/Packages.tsx
- src/components/common/ScrollToTop.tsx
- src/screens/Home.tsx
scroll to top button added
✅ Closes: #52
> feat: 🎸 added scroll to top button

- src/components/PackageRelated/PackageStatus.tsx
fixed scroll problem on installing page
✅ Closes: #72
> fix: 🐛 scroll problem for toast

- src/components/PackageRelated/PackageStatus.tsx
- src/components/SystemConfig/KernelComponent.tsx
- src/components/SystemConfig/SystemFastestMirror.tsx
> fix: 🐛 toast fixes

- src/components/PackageRelated/PackageStatus.tsx
> fix: 🐛 tty error

- src/data/apps.json
added a few apps to list
✅ Closes: #36
> fix: 🐛 added a few app to list

- public/GnomeLayouts/gnomepreview.svg
- public/GnomeLayouts/manjaropreview.svg
- public/GnomeLayouts/material-shellpreview.svg
- public/GnomeLayouts/traditionalpreview.svg
- src-tauri/tauri.conf.json
- src/components/SystemConfig/GnomeLayoutMaganer.tsx
- src/components/SystemConfig/SystemConfig.tsx
- src/translations/en.json
added gnome layout manager as model
> feat: 🎸 added embeded GLM

- src-tauri/tauri.conf.json
- src/components/SystemConfig/SystemConfig.tsx
manjaro control panel added
✅ Closes: #83
> feat: 🎸 mcp support

- package.json
- src/components/PackageRelated/Packages.tsx
- yarn.lock
> feat: 🎸 slider for packages

- src/screens/Home.tsx
- src/translations/en.json
added step description, clickable steps, check icon
> feat: 🎸 added step description, clickable steps, check icon

- src/components/StartLaunch.tsx
fixed start launch default toggled problem
> fix: 🐛 fixed start launch default toggled problem

- src/components/LanguageComponent.tsx
default language fix
✅ Closes: #103
> fix: 🐛 default language fix applied

- src/components/PackageRelated/Packages.tsx
- src/components/SystemConfig/GnomeLayoutMaganer.tsx
- src/components/SystemConfig/ManjaroSettingsModule.tsx
- src/components/SystemConfig/SystemFastestMirror.tsx
- src/components/SystemConfig/SystemUpdate.tsx
button width problem fixes
✅ Closes: #119
> fix: 🐛 button width problem fixes

- src/index.tsx
step background fixed on light theme
✅ Closes: #109
> fix: 🐛 step background fixes

- src-tauri/tauri.conf.json
- src/components/Home/LiveInstaller.tsx
calamares command updated
✅ Closes: #124
> fix: 🐛 live calamares command changed

- src/components/ResultComponent.tsx
return first button changed
✅ Closes: #133
> fix: 🐛 return button changed

- src/components/SystemConfig/GnomeLayoutMaganer.tsx
showing which gnome layout selected
I need to check cli. We have some problem to set selection to conf file using cli commands.
> fix: 🐛 showing which layout applied

- src/translations/de.json
- src/translations/en.json
Adaptions to German and English translation. Thanks.
> DE and EN translation

- src/components/Home/HomeContent.tsx
- src/components/Home/ManjaroVersion.tsx
- src/components/Home/ReleaseNotes.tsx
- src/components/NavbarComponent.tsx
added release and codename info
✅ Closes: #139
> feat: 🎸 added release and codename info

- src/components/Home/Info.tsx
fixed background of more model
✅ Closes: #149
> fix: 🐛 fixed background of more model

- src-tauri/src/main.rs
- src/components/PackageRelated/PackageDetail.tsx
hot fixes for not exists icon
✅ Closes: #142
> fix: 🐛 hot fixes for not exists icon

- src/components/SystemConfig/GnomeLayoutMaganer.tsx
- src/components/SystemConfig/KernelComponent.tsx
- src/components/SystemConfig/ManjaroSettingsModule.tsx
- src/components/SystemConfig/MirrorList.tsx
- src/components/SystemConfig/Mirrors.tsx
- src/components/SystemConfig/SystemConfig.tsx
- src/components/SystemConfig/SystemUpdate.tsx
conf style fixes
✅ Closes: #174
> fix: 🐛 conf style fixes

- src/components/PackageRelated/PackageStatus.tsx
- src/components/SystemConfig/KernelComponent.tsx
- src/components/SystemConfig/Mirrors.tsx
- src/components/SystemConfig/SystemUpdate.tsx
- src/screens/Home.tsx
- src/stores/ConnectionStore.ts
- src/translations/en.json
offline mode added
✅ Closes: #34
> feat: 🎸 offline mode added

- src/components/SystemConfig/SystemUpdate.tsx
- src/translations/en.json
Directly update support
✅ Closes: #179
> feat: 🎸 Directly update support

- src/index.tsx
- src/screens/App.tsx
removed right click context menu
✅ Closes: #40
> fix: 🐛 removed right click context menu

- package.json
- src-tauri/tauri.conf.json
- src/components/AppSetting/LanguageComponent.tsx
- src/i18n.ts
- yarn.lock
default language selection problem fixed
✅ Closes: #103
> fix: 🐛 default language fixes

- src/components/PackageRelated/PackageStatus.tsx
- src/stores/PackageStore.ts
added cancel button for package installation
> feat: 🎸 added cancel button for package installation

- package.json
- src/components/Home/Info.tsx
- src/components/Home/LiveInstaller.tsx
- src/components/Home/ManjaroVersion.tsx
- src/components/Home/ReleaseNotes.tsx
- src/components/StepButtons.tsx
- src/screens/App.tsx
- src/screens/HomeScreen.tsx
- src/translations/en.json
- yarn.lock
> fix: 🐛 homescreen changes

- src/components/SystemConfig/SystemUpdate.tsx
- src/translations/en.json
> fix: 🐛 updated update status badge colors

- package.json
- src-tauri/tauri.conf.json
- src/components/PackageRelated/Search/HandleSearch.ts
- src/components/PackageRelated/Search/SearchManjaro.d.ts
- src/components/PackageRelated/Search/SearchPackageComponent.tsx
- src/components/PackageRelated/Search/SearchPackageModelComponent.tsx
- src/components/PackageRelated/Search/SearchResults.tsx
- src/screens/PackageScreen.tsx
- src/translations/en.json
- yarn.lock
added search box for explorer page
> feat: 🎸 added search box for explorer page

- src/screens/PackageScreen.tsx
package arrow problem fixed
✅ Closes: #259
> fix: 🐛 package arrow problem fixed

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src/components/systemconfig/FsTrimServiceComponent.tsx
- src/screens/ConfigurationScreen.tsx
- src/translations/en.json
> feat: 🎸 added fstrim configuration

- src-tauri/tauri.conf.json
scope problem fixed
✅ Closes: #262
> fix: 🐛 scope problem fixed

- src/screens/ConfigurationScreen.tsx
removed hdd controller
✅ Closes: #286
> fix: 🐛 removed hdd controller

- src/screens/ConfigurationScreen.tsx
- src/screens/PackageScreen.tsx
- src/stores/ConfTabStore.ts
- src/stores/ExplorerTabStore.ts
fixed tab index problem when language changed
✅ Closes: #157
> fix: 🐛 fixed tab index problem when language changed

- src/components/systemconfig/FsTrimServiceComponent.tsx
- src/translations/en.json
service disable enable optimization
✅ Closes: #290
> fix: 🐛 service disable enable optimization

- src/components/systemconfig/FsTrimServiceComponent.tsx
> fix: 🐛 added command history to fstrim component

- src/screens/PackageScreen.tsx
fixed space problem for explorer page
✅ Closes: #304
> fix: 🐛 fixed space problem

- README.md
Corrected dependency names and `pacman` command
https://wiki.manjaro.org/index.php/System_Maintenance#Avoiding_Partial_Updates
> A few corrections

- src-tauri/tauri.conf.json
- src/components/systemconfig/GpuInfoComponent.tsx
- src/components/systemconfig/SystemInfo.tsx
- src/hooks/useWindowDimensions.ts
- src/screens/App.tsx
- src/screens/ConfigurationScreen.tsx
- src/screens/HomeScreen.tsx
- src/screens/PackageScreen.tsx
- src/translations/en.json
> fix: 🐛 some design problems

- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src/components/common/RootDetector.tsx
- src/index.tsx
- src/translations/en.json
✅ Closes: #319
Showing modal and close the application when open manjaro starter with root user.
Fixes #319 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Manjaro version: > 22.6
* Hardware: -
> feat: 🎸 root detector added

- src/components/systemconfig/GpuInfoComponent.tsx
- src/components/systemconfig/SystemInfo.tsx
- src/utils/Format.ts
✅ Closes: #332
Unit problem fixed
Fixes #332
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
**Test Configuration**:
* Manjaro version: next version
* Hardware:
> fix: 🐛 system info unit problem fixed

- src/components/appSetting/AboutComponent.tsx
- src/components/appSetting/AppSettings.tsx
- src/components/appSetting/BugReport.tsx
- src/components/appSetting/Changelog.tsx
- src/components/appSetting/LanguageComponent.tsx
- src/components/appSetting/StartLaunch.tsx
- src/translations/en.json
✅ Closes: #316
Bug report button
Fixes #316
> feat: 🎸 added bug report button

- src/translations/fr.json
Add new translations from en.json file.
> Update fr.json file

- package-lock.json
- package.json
- src/components/common/CommandHistory.tsx
- src/components/packageRelated/PackageStatus.tsx
- src/components/systemConfig/FsTrimServiceComponent.tsx
- src/components/systemConfig/KernelComponent.tsx
- src/components/systemConfig/Mirrors.tsx
- src/components/systemConfig/SystemUpdate.tsx
- src/stores/CommandStore.ts
- src/translations/en.json
- yarn.lock
✅ Closes: #324
Added copy command and removed showing log in command history panel
Fixes #324 
> fix: 🐛 removed logs from command history and some changes

- src/components/appSetting/AboutComponent.tsx
> fix: 🐛 fixed bug report button problem

- src/components/common/CommandHistory.tsx
- src/components/systemConfig/FsTrimServiceComponent.tsx
> fix: 🐛 fixed fstrim problem

- src/components/common/ConfirmPopComponent.tsx
- src/components/systemConfig/FsTrimServiceComponent.tsx
- src/components/systemConfig/KernelComponent.tsx
- src/components/systemConfig/SystemUpdate.tsx
- src/components/systemConfig/mirrors/fastest/FastestMirrorComponent.tsx
- src/translations/en.json
✅ Closes: #323
Added confirmation popup for fastest mirror, kernel installation, fstrim service.
Fixes #323 
Click Set fastest mirror button or install kernel button or enable-disable fstrim service button.
> fix: 🐛 added confirmation popup

- src-tauri/tauri.conf.json
- src/assets/Commands.ts
- src/components/systemConfig/mirrors/MirrorHelper.ts
- src/components/systemConfig/mirrors/MirrorMainComponent.tsx
- src/components/systemConfig/mirrors/activeBranch/ActiveBranchComponent.tsx
- src/translations/en.json
> feat: 🎸 added active branch badge to the mirror section

- src/translations/fr.json
Add new translations and modify hometext1.
> Last new update fr.json

- src/components/systemConfig/kernel/KernelListComponent.tsx
- src/translations/en.json
> fix: 🐛 install kernel tooltip fixes

- src/components/systemConfig/mirrors/MirrorMainComponent.tsx
- src/components/systemConfig/mirrors/activeBranch/ActiveBranchComponent.tsx
- src/translations/en.json
> fix: 🐛 added desc for current branch badge

- src/components/systemConfig/mirrors/MirrorMainComponent.tsx
- src/components/systemConfig/mirrors/repo/ShowRepoDetails.tsx
- src/screens/App.tsx
- src/translations/en.json
> fix: 🐛 added repo button and removed version info

- src/components/common/ConfirmPopComponent.tsx
- src/components/systemConfig/FsTrimServiceComponent.tsx
- src/components/systemConfig/kernel/KernelListComponent.tsx
- src/components/systemConfig/mirrors/fastest/FastestMirrorComponent.tsx
- src/translations/en.json
> feat: 🎸 added confirm popup commands

- package.json
- src/assets/Commands.ts
- src/components/common/ConfirmPopComponent.tsx
- src/components/systemConfig/mirrors/MirrorHelper.ts
- src/components/systemConfig/mirrors/MirrorMainComponent.tsx
- src/components/systemConfig/mirrors/country/CountryList.tsx
- src/components/systemConfig/mirrors/country/CountryModal.tsx
- src/components/systemConfig/mirrors/country/useCountryHook.ts
- src/stores/CountryStore.ts
- src/translations/en.json
- yarn.lock
> feat: 🎸 added custom mirror pool by country selection

- src/components/common/ConfirmPopComponent.tsx
> fix: 🐛 fixes confirm popup for packages

- src/components/systemConfig/mirrors/MirrorMainComponent.tsx
> fix: 🐛 overflow problem fixed

- src/assets/data/apps.json
- src/components/systemConfig/SystemUpdate.tsx
> fix: 🐛 removed aur package

- .github/workflows/deploymentCheck.yml
- .github/workflows/release.yml
- .vscode/settings.json
- README.md
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src/components/NavbarComponent.tsx
- src/components/common/CloseAppComponent.tsx
- src/translations/en.json
> feat: 🎸 added tray icon

- src-tauri/tauri.conf.json
- src/components/packageRelated/PackageStatus.tsx
- src/components/systemConfig/FsTrimServiceComponent.tsx
- src/components/systemConfig/SystemUpdate.tsx
- src/components/systemConfig/kernel/useKernelHook.ts
- src/components/systemConfig/mirrors/country/useCountryHook.ts
- src/components/systemConfig/mirrors/fastest/useFastestMirrorHook.ts
- src/hooks/useToastCustom.tsx
> fix: 🐛 code improvements and fstrim result popup

- .eslintrc.json
- src-tauri/tauri.conf.json
- src/components/appSetting/LanguageComponent.tsx
- src/components/appSetting/StartLaunch.tsx
- src/components/common/RootDetector.tsx
- src/components/common/environment/useEnvHook.ts
- src/components/common/remotePackage/useRemoteHook.ts
- src/components/packageRelated/PackageDetail.tsx
- src/components/systemConfig/GnomeLayoutMaganer.tsx
- src/components/systemConfig/mirrors/MirrorHelper.ts
- src/i18n.ts
- src/index.tsx
- src/initial/App.tsx
> refactor: 💡 code imp

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
> feat: 🎸 single instance plugin added

- src/components/NavbarComponent.tsx
> fix: 🐛 removed popup when clicking close button

- src/components/systemConfig/mirrors/country/CountryList.tsx
> fix: 🐛 mirror country problem fixed

- .vscode/settings.json
- README.md
- src-tauri/tauri.conf.json
> fix: 🐛 remove mhwd dependency(we use pamac now)

- src/components/systemConfig/kernel/KernelHelper.ts
- src/components/systemConfig/kernel/useKernelHook.ts
> fix: 🐛 fixed kernel installation problem

- src-tauri/tauri.conf.json
- src/components/NavbarComponent.tsx
- src/components/common/CommandHistory.tsx
- src/components/common/ConfirmPopComponent.tsx
- src/components/common/search/SearchModelComponent.tsx
- src/components/home/LearnMoreComponent.tsx
- src/components/home/LiveInstaller.tsx
- src/components/home/ReleaseNotes.tsx
- src/components/packageRelated/PackageDetail.tsx
- src/components/packageRelated/PackageStatus.tsx
- src/components/systemConfig/kernel/KernelListComponent.tsx
- src/components/systemConfig/mirrors/country/CountryModal.tsx
- src/components/systemConfig/mirrors/showing/ShowMirrorListComponent.tsx
- src/initial/App.tsx
- src/screens/ConfigurationScreen.tsx
- src/screens/FinalScreen.tsx
- src/screens/HomeScreen.tsx
- src/screens/PackageScreen.tsx
> fix: 🐛 reduced min screen and default screen size and fixes

- src/stores/LiveStore.ts
> fix: 🐛 showing installation button logic changed
